services:
  - type: web
    name: lamorta-backend
    runtime: node
    plan: free
    rootDir: lamorta-tattoo/backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
